
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE


