spring:
  application:
    name: @project.artifactId@
    version: @project.version@
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  flyway:
    url: jdbc:postgresql://localhost:5432/mydatabase
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}


